"""Generate visualizations for U.S. presidential elections (1976-2020).

This script reads aggregated election results and produces several
matplotlib/seaborn charts saved to the ``visualizations`` directory:
- Popular vote share by major party over time
- Popular vote margin (Democratic minus Republican)
- Electoral College outcomes by party
- Third-party popular vote share
"""
from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = PROJECT_ROOT / "data" / "elections_1976_2020.csv"
OUTPUT_DIR = PROJECT_ROOT / "visualizations"

sns.set_theme(style="whitegrid")
BLUE = "#2E77BB"
RED = "#C72525"
GREY = "#6B7280"


def load_election_data() -> pd.DataFrame:
    """Load election results and compute helper columns."""
    df = pd.read_csv(DATA_PATH)
    df["winner_party"] = df["winner_party"].astype("category")
    df["popular_vote_margin"] = df["democratic_popular_pct"] - df["republican_popular_pct"]
    return df


def plot_popular_vote_trends(df: pd.DataFrame) -> None:
    """Line plot of popular vote share for the two major parties."""
    plt.figure(figsize=(10, 6))
    plt.plot(df["year"], df["democratic_popular_pct"], marker="o", color=BLUE, label="Democratic popular vote %")
    plt.plot(df["year"], df["republican_popular_pct"], marker="o", color=RED, label="Republican popular vote %")
    plt.title("Popular Vote Share by Major Party (1976-2020)")
    plt.ylabel("Popular vote (%)")
    plt.xlabel("Year")
    plt.ylim(35, 65)
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "popular_vote_trends.png", dpi=300)
    plt.close()


def plot_popular_vote_margin(df: pd.DataFrame) -> None:
    """Bar chart of the popular vote margin (Democratic minus Republican)."""
    plt.figure(figsize=(10, 6))
    colors = [BLUE if margin >= 0 else RED for margin in df["popular_vote_margin"]]
    plt.bar(df["year"], df["popular_vote_margin"], color=colors)
    plt.axhline(0, color=GREY, linewidth=1.2, linestyle="--")
    plt.title("Popular Vote Margin (Democratic minus Republican)")
    plt.ylabel("Margin (percentage points)")
    plt.xlabel("Year")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "popular_vote_margin.png", dpi=300)
    plt.close()


def plot_electoral_votes(df: pd.DataFrame) -> None:
    """Stacked bar chart showing Electoral College totals by party."""
    plt.figure(figsize=(10, 6))
    plt.bar(df["year"], df["democratic_electoral_votes"], color=BLUE, label="Democratic EVs")
    plt.bar(
        df["year"],
        df["republican_electoral_votes"],
        bottom=df["democratic_electoral_votes"],
        color=RED,
        label="Republican EVs",
    )
    if (df["other_electoral_votes"] > 0).any():
        plt.bar(
            df["year"],
            df["other_electoral_votes"],
            bottom=df["democratic_electoral_votes"] + df["republican_electoral_votes"],
            color=GREY,
            label="Other EVs",
        )
    plt.title("Electoral College Results (1976-2020)")
    plt.ylabel("Electoral votes")
    plt.xlabel("Year")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "electoral_votes.png", dpi=300)
    plt.close()


def plot_third_party_share(df: pd.DataFrame) -> None:
    """Line chart of third-party popular vote share."""
    plt.figure(figsize=(10, 5))
    plt.plot(df["year"], df["third_party_pct"], marker="o", color=GREY)
    plt.title("Third-Party Popular Vote Share")
    plt.ylabel("Popular vote (%)")
    plt.xlabel("Year")
    plt.ylim(0, max(df["third_party_pct"]) + 5)
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "third_party_share.png", dpi=300)
    plt.close()


def save_summary_table(df: pd.DataFrame) -> None:
    """Save the core metrics to a markdown table for quick reference."""
    table_columns = [
        "year",
        "democratic_candidate",
        "republican_candidate",
        "democratic_popular_pct",
        "republican_popular_pct",
        "third_party_pct",
        "democratic_electoral_votes",
        "republican_electoral_votes",
        "other_electoral_votes",
        "winner_party",
    ]
    markdown_table = df[table_columns].to_markdown(index=False)
    (OUTPUT_DIR / "README.md").write_text(
        "# U.S. Presidential Elections (1976-2020)\n\n" "Data summary generated by scripts/visualize.py:\n\n" + markdown_table + "\n"
    )


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    df = load_election_data()
    plot_popular_vote_trends(df)
    plot_popular_vote_margin(df)
    plot_electoral_votes(df)
    plot_third_party_share(df)
    save_summary_table(df)
    print(f"Saved charts to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
